main:
  - identifier: home
    name: nav.home
    url: /
    weight: 1
    params:
      icon: home

  - identifier: posts
    name: nav.posts
    url: /posts/
    weight: 2
    params:
      icon: posts

  - identifier: discussions
    name: шоишо║
    url: /discussions/
    weight: 3
    params:
      icon: message-circle

  - identifier: projects
    name: nav.projects
    url: /projects/
    weight: 4
    params:
      icon: projects

  - name: nav.categories
    pageRef: /categories
    weight: 30
    params:
      icon: categories
      
  - name: nav.tags
    pageRef: /tags
    weight: 40
    params:
      icon: tags

  - identifier: archives
    name: nav.archives
    url: /archives/
    weight: 50
    params:
      icon: archive



# footer menu
footer:
  - name: About
    pageRef: /about
    weight: 10
    params:
      icon: about
  - name: Contact
    url: https://google.com
    weight: 20
    params:
      icon: contact
  - name: RSS Feed
    url: /index.xml
    weight: 30
    params:
      icon: rss

# footer social link
social:
  - name: GitHub
    url: https://github.com/caifangwen
    weight: 10
    params:
      icon: github
  - name: Twitter
    url: https://twitter.com/username
    weight: 20
    params:
      icon: twitter
  - name: LinkedIn
    url: https://linkedin.com/in/username
    weight: 30
    params:
      icon: linkedin
  - name: Email
    url: mailto:frida_cai@qq.com
    weight: 40
    params:
      icon: email

