baseURL = "/"
title = "Frida Cai"
languageCode = "zh-cn"
theme = "hugo-narrow"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # 允许渲染 Demo 中的 HTML 标签

[params]
  # 某些主题需要明确指定环境
  env = "development"
